name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Configure git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Check git status
      run: git status

    - name: Show git remote
      run: git remote -v
