name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false
        
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install
        
    - name: Jekyll build
      run: |
        bundle exec jekyll build --destination ./_site
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v4
      with:
        path: ./_site